# Generated by Django 5.2.13 on 2026-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_internalchatroom_internalmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internalchatroom",
            name="member",
        ),
        migrations.RemoveField(
            model_name="internalmessage",
            name="sender",
        ),
        migrations.AddField(
            model_name="internalchatroom",
            name="member_id",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="sender_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="sender_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
