# Generated by Django 5.2.13 on 2026-06-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_alter_bulkcampaignattachment_table_and_more"),
        ("chat", "0004_remove_internalchatroom_member_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignTeamChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("creative", "Creative Team"),
                            ("campaign_team", "Campaign Team"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_chat_rooms",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "team_type")},
            },
        ),
        migrations.CreateModel(
            name="CampaignTeamMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.IntegerField()),
                ("sender_name", models.CharField(blank=True, max_length=150)),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("member", "Team Member"), ("admin", "Admin")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="campaign_team_chat/files/"
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.campaignteamchatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
