# Generated by Django 5.2.13 on 2026-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_campaignteamchatroom_campaignteammessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tagged_line_item",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
