# Generated by Django 5.2.13 on 2026-05-06 16:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('reporting_id', models.CharField(blank=True, max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('agency_type', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('billing_currency', models.CharField(default='INR', max_length=20)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('cin_number', models.CharField(blank=True, max_length=50)),
                ('vast_number', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.CharField(max_length=200)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('campaign_name', models.CharField(max_length=300)),
                ('client_campaign_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_type', models.CharField(max_length=50)),
                ('buying_type', models.CharField(max_length=60)),
                ('objective', models.CharField(max_length=100)),
                ('campaign_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('geo_targeting', models.TextField()),
                ('platforms', models.CharField(max_length=300)),
                ('frequency_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('brand_safety', models.CharField(max_length=20)),
                ('viewability_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('client', 'Client')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_period_days', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('tax_type', models.CharField(blank=True, max_length=50)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_section', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('outstanding_limit', models.FloatField(blank=True, null=True)),
                ('billing_currency', models.CharField(default='INR', max_length=20)),
                ('billing_contact', models.CharField(blank=True, max_length=100)),
                ('advance_amount', models.FloatField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=50)),
                ('payment_behavior', models.CharField(blank=True, max_length=100)),
                ('avg_response_time', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('additional_internal_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_tags', models.CharField(blank=True, max_length=400, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_manager', models.CharField(max_length=100)),
                ('sales_owner', models.CharField(max_length=100)),
                ('campaign_manager', models.CharField(max_length=100)),
                ('finance_owner', models.CharField(max_length=100)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('address_line1', models.TextField(blank=True)),
                ('address_line2', models.TextField(blank=True)),
                ('digital_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('line_item_name', models.CharField(max_length=300)),
                ('ethnicity', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ad_format', models.JSONField(blank=True, null=True)),
                ('impressions', models.BigIntegerField(blank=True, null=True)),
                ('landing_page', models.URLField(blank=True, null=True)),
                ('units', models.BigIntegerField(blank=True, null=True)),
                ('ctr', models.IntegerField(blank=True, null=True)),
                ('viewability', models.IntegerField(blank=True, null=True)),
                ('vcr', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='app.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_name', models.CharField(max_length=300)),
                ('main_asset', models.FileField(blank=True, null=True, upload_to='creatives/main/')),
                ('backup_image', models.FileField(blank=True, null=True, upload_to='creatives/backup/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=30)),
                ('main_asset_name', models.CharField(blank=True, max_length=255)),
                ('backup_image_name', models.CharField(blank=True, max_length=255)),
                ('click_through_url', models.URLField(blank=True, null=True)),
                ('appended_html_tag', models.TextField(blank=True)),
                ('integration_code', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives_detail', to='app.lineitem')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
