# Generated by Django 5.2.13 on 2026-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='ctr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
