# Generated by Django 5.2.13 on 2026-05-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='backup_image_name',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='main_asset_name',
        ),
    ]
