# Generated by Django 5.2.13 on 2026-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lineitem_ctr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='ctr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
