# Generated by Django 5.2.13 on 2026-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('advertiser', models.CharField(max_length=200)),
                ('business_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('campaign_name', models.CharField(max_length=300)),
                ('campaign_code', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_type', models.CharField(choices=[('Brand Awareness', 'Brand Awareness'), ('Performance', 'Performance'), ('Retargeting', 'Retargeting'), ('Prospecting', 'Prospecting'), ('Lead Generation', 'Lead Generation')], max_length=50)),
                ('buying_type', models.CharField(choices=[('Programmatic (DV360)', 'Programmatic (DV360)'), ('Direct', 'Direct'), ('Programmatic Guaranteed', 'Programmatic Guaranteed'), ('Preferred Deal', 'Preferred Deal'), ('Open Auction', 'Open Auction')], max_length=60)),
                ('objective', models.CharField(choices=[('Increase Brand Awareness', 'Increase Brand Awareness'), ('Drive Website Traffic', 'Drive Website Traffic'), ('Generate Leads', 'Generate Leads'), ('Boost Sales', 'Boost Sales'), ('App Installs', 'App Installs')], max_length=100)),
                ('kpis', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('primary_objective', models.CharField(choices=[('Reach', 'Reach'), ('Brand Awareness', 'Brand Awareness'), ('Traffic', 'Traffic'), ('Engagement', 'Engagement'), ('Video Views', 'Video Views'), ('Conversions', 'Conversions')], max_length=50)),
                ('target_audience', models.CharField(choices=[('General Market', 'General Market'), ('Adults 18–35', 'Adults 18–35'), ('Women 25–45', 'Women 25–45'), ('Urban Youth', 'Urban Youth'), ('Custom Segment', 'Custom Segment')], max_length=50)),
                ('geo_targeting', models.CharField(max_length=500)),
                ('platforms', models.CharField(max_length=500)),
                ('frequency_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('brand_safety', models.CharField(choices=[('Standard', 'Standard'), ('Strict', 'Strict'), ('Custom', 'Custom')], max_length=20)),
                ('viewability_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_type', models.CharField(choices=[('total', 'Total Budget'), ('daily', 'Daily Budget')], max_length=10)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pacing', models.CharField(choices=[('Even', 'Even'), ('Front-Loaded', 'Front-Loaded'), ('Back-Loaded', 'Back-Loaded'), ('ASAP', 'ASAP')], max_length=20)),
                ('day_parting', models.CharField(blank=True, choices=[('All Day', 'All Day'), ('Business Hours (9am–6pm)', 'Business Hours (9am–6pm)'), ('Prime Time (6pm–11pm)', 'Prime Time (6pm–11pm)'), ('Custom', 'Custom')], max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, choices=[('Asia/Kolkata (IST)', 'Asia/Kolkata (IST)'), ('UTC', 'UTC'), ('America/New_York (EST)', 'America/New_York (EST)'), ('Europe/London (GMT)', 'Europe/London (GMT)')], max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
