# Generated by Django 5.2.13 on 2026-05-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lineitem_ctr_alter_lineitem_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='landing_page',
        ),
    ]
