# Generated by Django 5.2.13 on 2026-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_lineitem_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='landing_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
