# Generated by Django 5.2.13 on 2026-05-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lineitem_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='click_through_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
