# Generated by Django 5.2.13 on 2026-05-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_creative_click_through_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='landing_page',
        ),
    ]
