# Generated by Django 5.2.13 on 2026-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lineitem_lineitemcreative'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='units',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
