# Generated by Django 5.2.13 on 2026-05-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_lineitem_landing_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='thirdparty/files/')),
                ('backup_image', models.FileField(blank=True, null=True, upload_to='thirdparty/backup/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_creatives', to='app.lineitem')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
