# Generated by Django 5.2.13 on 2026-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_thirdpartycreative'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
