# Generated by Django 5.2.13 on 2026-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lineitem_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='ctr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='vcr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='viewability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
