# Generated by Django 5.2.13 on 2026-05-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lineitem_ctr_lineitem_vcr_lineitem_viewability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_name', models.CharField(max_length=300)),
                ('main_asset', models.FileField(blank=True, null=True, upload_to='creatives/main/')),
                ('backup_image', models.FileField(blank=True, null=True, upload_to='creatives/backup/')),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=30)),
                ('main_asset_name', models.CharField(blank=True, max_length=255)),
                ('main_asset_mime', models.CharField(blank=True, max_length=100)),
                ('backup_image_name', models.CharField(blank=True, max_length=255)),
                ('backup_image_mime', models.CharField(blank=True, max_length=100)),
                ('click_through_url', models.URLField(blank=True, null=True)),
                ('appended_html_tag', models.TextField(blank=True)),
                ('integration_code', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives_detail', to='app.lineitem')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
