# Generated by Django 5.2.13 on 2026-05-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_creative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='backup_image_mime',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='main_asset_mime',
        ),
    ]
