# Generated by Django 5.2.13 on 2026-05-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_creative_backup_image_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='line_item_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
