# Generated by Django 5.2.13 on 2026-05-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='unit_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
