# Generated by Django 5.2.13 on 2026-05-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lineitem_line_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='app.campaign'),
        ),
    ]
