# Generated by Django 5.2.13 on 2026-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_lineitem_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
