# Generated by Django 5.2.13 on 2026-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lineitem_unit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='unit_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
