# Generated by Django 5.2.13 on 2026-05-19 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_lineitem_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('client_password', models.CharField(max_length=200)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clients', to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_approval', to='app.client')),
            ],
        ),
    ]
