# Generated by Django 5.2.13 on 2026-05-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='approved_by',
        ),
    ]
