# Generated by Django 5.2.13 on 2026-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('client', 'Client'), ('creative', 'Creative'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
