# Generated by Django 5.2.13 on 2026-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_teamaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamaccess',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
