# Generated by Django 5.2.13 on 2026-05-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='reporting_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
