# Generated by Django 5.2.13 on 2026-05-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_client_reporting_id_campaign_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='new_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
