# Generated by Django 5.2.13 on 2026-06-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_fcmtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user',
        ),
    ]
