# Generated by Django 5.2.13 on 2026-06-01 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_fcmtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
