# Generated by Django 5.2.13 on 2026-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='creative_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartycreative',
            name='creative_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
