# Generated by Django 5.2.13 on 2026-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_creative_creative_id_thirdpartycreative_creative_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='age',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='brand_safety',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='frequency_cap',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='geo_targeting',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='new_cpm',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='viewability_goal',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='brand_safety',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='frequency_cap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='geo_targeting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='platforms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='viewability_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
