# Generated by Django 5.2.13 on 2026-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_campaign_age_remove_campaign_brand_safety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='new_cpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
