# Generated by Django 5.2.13 on 2026-06-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_campaign_campaign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='insertion_orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insertion_order', to='app.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertion_orders', to='app.client')),
            ],
        ),
    ]
