# Generated by Django 5.2.13 on 2026-06-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='excel_reports/')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excel_report', to='app.campaign')),
            ],
        ),
    ]
