# Generated by Django 5.2.13 on 2026-06-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_invoice_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='viewability_goal',
        ),
    ]
