# Generated by Django 5.2.13 on 2026-06-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_lineitem_viewability_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignexcel',
            name='report_type',
            field=models.CharField(choices=[('cpm', 'CPM (Impressions Booked)'), ('cpc', 'CPC (Clicks Booked)')], default='cpm', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignexcel',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_reports', to='app.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignexcel',
            unique_together={('campaign', 'report_type')},
        ),
    ]
