# Generated by Django 5.2.13 on 2026-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_campaignexcel_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignexcel',
            name='line_item_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
