# Generated by Django 5.2.13 on 2026-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_campaignexcel_line_item_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignexcel",
            name="publish_status",
            field=models.CharField(
                blank=True,
                choices=[("published", "Published")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
