# Generated by Django 5.2.13 on 2026-06-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("company_type", models.CharField(max_length=100)),
                ("agency_type", models.CharField(blank=True, max_length=100)),
                ("brand", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("billing_currency", models.CharField(default="INR", max_length=20)),
                ("address_line1", models.TextField()),
                ("address_line2", models.TextField(blank=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                ("cin_number", models.CharField(max_length=50)),
                ("vast_number", models.CharField(max_length=100)),
                ("place_of_supply", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_period_days", models.IntegerField()),
                ("payment_type", models.CharField(max_length=50)),
                ("payment_terms", models.CharField(max_length=100)),
                ("tax_type", models.CharField(max_length=50)),
                ("tds_applicable", models.BooleanField(default=False)),
                ("tds_section", models.CharField(max_length=50)),
                ("credit_limit", models.FloatField()),
                ("outstanding_limit", models.FloatField()),
                ("billing_currency", models.CharField(default="INR", max_length=20)),
                ("billing_contact", models.CharField(max_length=100)),
                ("advance_amount", models.FloatField()),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_type", models.CharField(max_length=100)),
                ("priority", models.CharField(max_length=50)),
                ("risk_level", models.CharField(max_length=50)),
                ("payment_behavior", models.CharField(max_length=100)),
                ("avg_response_time", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "additional_internal_notes",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "additional_tags",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_manager", models.CharField(max_length=100)),
                ("sales_owner", models.CharField(max_length=100)),
                ("campaign_manager", models.CharField(max_length=100)),
                ("finance_owner", models.CharField(max_length=100)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line1", models.TextField()),
                ("address_line2", models.TextField(blank=True)),
                ("country", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("designation", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                ("address_line1", models.TextField()),
                ("address_line2", models.TextField(blank=True)),
                (
                    "digital_signature",
                    models.FileField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
