# Generated by Django 5.2.13 on 2026-06-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teamaccess_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamaccess",
            name="user",
        ),
    ]
