# Generated by Django 5.2.13 on 2026-06-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("cpm", "CPM (Impressions Booked)"),
                            ("cpc", "CPC (Clicks Booked)"),
                        ],
                        default="cpm",
                        max_length=10,
                    ),
                ),
                ("excel_file", models.FileField(upload_to="excel_reports/")),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("line_item_overrides", models.JSONField(blank=True, default=dict)),
                (
                    "publish_status",
                    models.CharField(
                        blank=True,
                        choices=[("published", "Published")],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_reports",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "report_type")},
            },
        ),
        migrations.CreateModel(
            name="CampaignLineItemExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("cpm", "CPM"), ("cpc", "CPC")],
                        default="cpm",
                        max_length=10,
                    ),
                ),
                ("impressions", models.BigIntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("units", models.CharField(blank=True, max_length=100, null=True)),
                ("ctr", models.FloatField(blank=True, null=True)),
                ("viewability", models.FloatField(blank=True, null=True)),
                ("vcr", models.FloatField(blank=True, null=True)),
                ("kpi_notes", models.TextField(blank=True, null=True)),
                ("sitelist", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_item_excel_data",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "line_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_data",
                        to="campaigns.lineitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("line_item", "report_type")},
            },
        ),
    ]
