# Generated by Django 5.2.13 on 2026-06-16 11:41

from django.db import migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignLineItemExcelDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("cpm", "CPM"), ("cpc", "CPC")],
                        default="cpm",
                        max_length=10,
                    ),
                ),
                ("impressions", models.BigIntegerField(blank=True, null=True)),
                ("clicks", models.BigIntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("target_cpm", models.FloatField(blank=True, null=True)),
                ("target_ctr", models.FloatField(blank=True, null=True)),
                ("target_cpc", models.FloatField(blank=True, null=True)),
                ("booked_budget", models.FloatField(blank=True, null=True)),
                ("sitelist", models.TextField(blank=True, null=True)),
                (
                    "advertiser_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_item_excel_data",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_data",
                        to="campaigns.lineitem",
                    ),
                ),
            ],
            options={"unique_together": {("line_item", "report_type")}},
        ),
    ]
