# Generated by Django 5.2.13 on 2026-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_create_line_item_excel_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlineitemexceldetails",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
