# Generated by Django 5.2.13 on 2026-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_campaigndailyreportexcel_campaigndailyentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndailyentry",
            name="measurable_impression",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaigndailyentry",
            name="media_cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="campaigndailyentry",
            name="revenue",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="campaigndailyentry",
            name="video_end",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaigndailyentry",
            name="video_start",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaigndailyentry",
            name="viewable_impression",
            field=models.BigIntegerField(default=0),
        ),
    ]
