# Generated by Django 5.2.13 on 2026-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_campaigndailyentry_measurable_impression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndailyentry",
            name="vcr",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="campaigndailyentry",
            name="viewability",
            field=models.FloatField(default=0),
        ),
    ]
