# Generated by Django 5.2.13 on 2026-06-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser", models.CharField(max_length=200)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("campaign_name", models.CharField(max_length=300)),
                (
                    "client_campaign_ID",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purchase_order_ID",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("campaign_type", models.CharField(max_length=50)),
                ("buying_type", models.CharField(max_length=60)),
                ("objective", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "campaign_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("new_cpm", models.FloatField(blank=True, null=True)),
                ("new_price", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_item_id", models.CharField(max_length=50, unique=True)),
                ("line_item_name", models.CharField(max_length=300)),
                ("ethnicity", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("ad_format", models.JSONField()),
                ("impressions", models.BigIntegerField(blank=True, null=True)),
                ("units", models.CharField(blank=True, max_length=100, null=True)),
                ("ctr", models.FloatField(blank=True, null=True)),
                ("viewability", models.FloatField(blank=True, null=True)),
                ("vcr", models.FloatField(blank=True, null=True)),
                ("unit_cost", models.CharField(blank=True, max_length=100, null=True)),
                ("kpi_notes", models.TextField(blank=True, null=True)),
                ("unit_value", models.FloatField(blank=True, null=True)),
                ("age", models.CharField(blank=True, max_length=200, null=True)),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                ("geo_targeting", models.TextField(blank=True, null=True)),
                ("platforms", models.CharField(blank=True, max_length=300, null=True)),
                ("frequency_cap", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "brand_safety",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Creative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creative_name", models.CharField(max_length=300)),
                (
                    "main_asset",
                    models.FileField(
                        blank=True, null=True, upload_to="creatives/main/"
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=50)),
                ("aspect_ratio", models.CharField(blank=True, max_length=20)),
                ("file_size", models.CharField(blank=True, max_length=30)),
                (
                    "click_through_url",
                    models.URLField(blank=True, max_length=400, null=True),
                ),
                ("appended_html_tag", models.TextField(blank=True)),
                ("integration_code", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creative_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives_detail",
                        to="campaigns.lineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_file",
                    models.FileField(
                        blank=True, null=True, upload_to="thirdparty/files/"
                    ),
                ),
                (
                    "backup_image",
                    models.FileField(
                        blank=True, null=True, upload_to="thirdparty/backup/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creative_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_party_creatives",
                        to="campaigns.lineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
