# Generated by Django 5.2.13 on 2026-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="dv_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
