# Generated by Django 5.2.13 on 2026-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_lineitem_dv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="dv_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
