# Generated by Django 5.2.13 on 2026-06-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_alter_lineitem_dv_id"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkCampaignDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("advertiser", models.CharField(max_length=200)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "client_campaign_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purchase_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("campaign_name", models.CharField(max_length=300)),
                ("campaign_type", models.CharField(max_length=50)),
                (
                    "buying_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("objective", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("processed", "Processed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_campaign_requests",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "bulkcampaigndetails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkCampaignAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="bulk_campaign_attachments/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="campaigns.bulkcampaigndetails",
                    ),
                ),
            ],
            options={
                "db_table": "bulkcampaignattachments",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
