# Generated by Django 5.2.13 on 2026-06-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_bulkcampaigndetails_bulkcampaignattachment"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bulkcampaignattachment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="bulkcampaigndetails",
            table=None,
        ),
    ]
