# Generated by Django 5.2.13 on 2026-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_alter_bulkcampaignattachment_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "Live"),
                    ("upcoming", "Upcoming"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
